name: flutter_riverpod_template
description: "A new Flutter river pod project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.2.0
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.2.0
  retrofit: ^4.0.1
  dio: ^5.3.2
  build_runner:
  freezed:
  json_annotation: ^4.8.1
  flutter_hooks: ^0.20.5
  auto_route: ^8.1.3
  hooks_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  retrofit_generator: ^8.0.6
  riverpod_generator: ^2.3.9
  # used with freezed model
  json_serializable: ^6.7.1
  auto_route_generator: ^8.0.0

flutter:
  uses-material-design: true
